language: python
cache: pip

python:
  - "3.4"
  - "3.5"
  - "3.6"

before_install:
  - git fetch --unshallow || true

install:
  # get miniconda
  - wget -q https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b -p $PWD/anaconda
  - anaconda/bin/conda update --yes --quiet conda
  # install and extract ffmpg static binary to current directory
  - anaconda/bin/conda install --yes -c menpo ffmpeg=3.1.3
  - cp anaconda/bin/ffmpeg .
  - ./ffmpeg -version
  - export PATH=".:$PATH"

  - pip install -U pip setuptools
  - pip install --pre pybuilder
  - pyb -X install_dependencies

script:
  - pyb -X

deploy:
  provider: pypi
  user: esc
  server: https://upload.pypi.org/legacy/
  distributions: sdist
  skip_cleanup: true
  password:
    secure: "ThLHwunhHxHD/apvEckzuz+ydS/n19TkN6wm8FID2I5UviHfj34/F9ohtapJgAMnx6Dn4AyQAhfUv8kiftnmYX8ZZ4PnPe+pCWIQAnqrkDeq06tY2n28znim44FKgqwojr6lDF1prDPHDlr/K0wsc4m+o4b+3K1DA3BR6QZvJd+WxV3x9E5qeke5rsdgnDEWl0AL+r/UhP7ePYgzq8FAGCYRfJPgFLQUSC9y3jduaEQBhKaQWiuqLC1378vwSL49g7hDxbCEzZpJtil39W40kxt+mVVVlKvKtOtSzfZ8BEAb7mRpktjOEt5MVqKM/Gi3WsO0+ntprgzryzXr4frS5+F0uPwXBAyOC9Nj/sysL/livqXj5sHvkxBiPl0OzvCsPQn7F8qc0nJasxUfo5nUvmJke87trSHvjUCkMYEe/1kG+b93n2fOnBf6HlFADJCcOmZVTH1gUKAlIjOcqWMgvXP+c4eYxK1YL6xB/Klk5ipARkVDPXHgxRACnPXviXXHzkM04yjkF3JfbPr37JcvNnSMIIiyNqCp6UtPG6s2E06AA7qLGB3673HrBsXugIzTovz081fNDk91Jptiirm3nJ+8EvCIl/xUHo+GHcnrS1XLJvhYE1eTsPDvg5S04H336msnkrV9dbHE98aN93ZAiDjDuLFNZisz1zAKUeQTqoE="
  on:
    repo: TwentyBN/GulpIO
    python: '3.6'
    branch: master
